[package]
name = "resource_monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.151"
sensors-sys = { version = "0.2.10", features = ["static"] }
sys-info = "0.9.1"
